---
title: "Volume 6, Issue 1"
date: "2014-01-01"
page-layout: full
title-block-banner: true
toc: true
---

<div class="paper-card full-bleed">
  <p class="paper-links">
    <i class="fa-regular fa-file-pdf"></i>
    <a href="RJ-2014-1.pdf">Download Complete Issue (PDF)</a>
  </p>
  <div class="paper-citation">Published June 2014</div>
</div>

## Table of Contents

[Editorial](../../news/RJ-2014-1-editorial/) (p. 3)<br>*Deepayan Sarkar*

### Contributed Research Articles

[Taming PITCHf/x Data with XML2R and pitchRx](../../articles/RJ-2014-001/) (p. 5)<br>*Carson Sievert*

[A Multiscale Test of Spatial Stationarity for Textured](../../articles/RJ-2014-002/) (p. 20)<br>*Matthew A. Nunes, Sarah L. Taylor, Idris A. Eckley*

[Stratified Weibull Regression Model for Interval-Censored](../../articles/RJ-2014-003/) (p. 31)<br>*Xiangdong Gu, David Shapiro, Michael D. Hughes and*

[brainR: Interactive 3 and 4D Images of High Resolution](../../articles/RJ-2014-004/) (p. 41)<br>*John Muschelli, Elizabeth Sweeney, Ciprian Crainiceanu*

[The RWiener Package: an R Package Providing Distribution](../../articles/RJ-2014-005/) (p. 49)<br>*Dominik Wabersich, Joachim Vandekerckhove*

[PivotalR: A Package for Machine Learning on Big Data](../../articles/RJ-2014-006/) (p. 57)<br>*Hai Qian*

[rotations: An R Package for SO(3) Data](../../articles/RJ-2014-007/) (p. 68)<br>*Bryan Stanfill, Heike Hofmann, Ulrike Genschel*

[ROSE: a Package for Binary Imbalanced Learning](../../articles/RJ-2014-008/) (p. 79)<br>*Nicola Lunardon, Giovanna Menardi, Nicola Torelli*

[investr: An R Package for Inverse Estimation](../../articles/RJ-2014-009/) (p. 90)<br>*Brandon M. Greenwell, Christine M. Schubert Kabban*

[Rankcluster: An R Package for Clustering Multivariate](../../articles/RJ-2014-010/) (p. 101)<br>*Julien Jacques, Quentin Grimonprez, Christophe*

[The stringdist Package for Approximate String Matching](../../articles/RJ-2014-011/) (p. 111)<br>*Mark P.J. van der Loo*

[RStorm: Developing and Testing Streaming Algorithms in R](../../articles/RJ-2014-012/) (p. 123)<br>*Maurits Kaptein*

[The gridSVG Package](../../articles/RJ-2014-013/) (p. 133)<br>*Paul Murrell, Simon Potter*

[MRCV: A Package for Analyzing Categorical Variables with](../../articles/RJ-2014-014/) (p. 144)<br>*Natalie A. Koziol, Christopher R. Bilder*

[Archiving Reproducible Research with R and Dataverse](../../articles/RJ-2014-015/) (p. 151)<br>*Thomas J. Leeper*

[oligoMask: A Framework for Assessing and Removing the Effect](../../articles/RJ-2014-018/) (p. 159)<br>*Daniel Bottomly, Beth Wilmot, Shannon K. McWeeney*

[sgr: A Package for Simulating Conditional Fake Ordinal Data](../../articles/RJ-2014-019/) (p. 164)<br>*Luigi Lombardi, Massimiliano Pastore*

[Web Technologies Task View](../../articles/RJ-2014-016/) (p. 178)<br>*Patrick Mair, Scott Chamberlain*

[Addendum to ``Statistical Software from a Blind Person's](../../articles/RJ-2014-017/) (p. 182)<br>*A. Jonathan R. Godfrey, Robert Erhardt*

### News and Notes

[News from the Bioconductor Project](../../news/RJ-2014-1-bioconductor/) (pp. 184-185)<br>*The Bioconductor Team*

[Changes on CRAN](../../news/RJ-2014-1-cran/) (pp. 186-220)<br>*Kurt Hornik, Achim Zeileis*

[Changes in R](../../news/RJ-2014-1-r-changes/) (pp. 221-235)<br>*The R Core Team*

[R Foundation News](../../news/RJ-2014-1-r-foundation/) (p. 183)<br>*Kurt Hornik*

[RJ 2014 016](../../news/RJ-2014-1-RJ-2014-016/)

[RJ 2014 017](../../news/RJ-2014-1-RJ-2014-017/)

