---
title: "The R Journal"
page-layout: full
title-block-banner: true
---

The R Journal is a peer-reviewed, open-access scientific journal, published by The R Foundation. It features short- to medium-length articles (up to 20 pages) covering topics of interest to users and developers of R. For example, description and implementation details of R packages, surveys or reviews of R software related to a particular area, applications of R software or descriptions of teaching resources related to R.

All submissions must primarily be about R packages and R programming. Submissions that involve R calling other software will be considered provided: (a) the other software is open source and free to use; (b) is widely used; and (c) there is a clear justification for using it rather than a native R implementation. Occasional exceptions may be made if (a) is not satisfied, provided there is no viable open source alternative.

The R Journal reaches a wide audience and has a thorough review process. It has a generally increasing [SJR impact factor](https://www.scimagojr.com/journalsearch.php?q=21100255423&tip=sid&exact=no). Papers are expected to be concise, clearly written, not too technical, clearly related to R, and follow reproducible practices. Additional technical details and examples could be included as supplementary material. Authors of refereed articles should take care to:

* put their contribution in context, in particular discuss related R functions or packages;
* explain the motivation for their contribution;
* provide code to reproduce the material in the paper.

## Article types

The R Journal accepts a variety of article topics including:

- **Packages:** Details of contributed R packages that are available on CRAN or Bioconductor, that go beyond a package vignette. This includes providing the broader context, implementation details, applications or examples of use, with the purpose being to make the work relevant to a wider readership than only the package users. The paper might explain the novelty in implementation and use of R, introduce new data structures or general architectures that could be re-usable for other R projects. Note that both the paper and the code will be reviewed. See our [guidelines for papers about R packages](R_package_guidelines.html).
- **Reviews and proposals:** surveying and discussing challenges and opportunities of potential importance for the broader R community, including proposals and proof-of-concept implementations.
- **Comparisons and benchmarking:** of implementations in base-R and contributed packages with each other, and where relevant with implementations in other software systems.
- **Applications:** demonstrating how new or existing techniques can be applied in an area of current interest using R, providing a fresh view of such analyses in R that is of benefit beyond the specific application.
- **Special issue articles:** papers associated with a conference like R Medicine, or possibly a collection of papers on a particular topic of interest.

## History

The R Journal was established in 2009, superseding the [R News](http://www.r-project.org/doc/Rnews/index.html). For historical purposes it also includes a news section, that includes items from R Core, updates from CRAN and Bioconductor, foRwards activities and conference reports.
