---
title: "Volume 17, Issue 2"
date: "2025-06-01"
page-layout: full
title-block-banner: true
toc: true
---

<div class="paper-card full-bleed">
  <p class="paper-links">
    <i class="fa-regular fa-file-pdf"></i>
    <a href="2025-2.pdf">Download Complete Issue (PDF)</a>
  </p>
  <div class="paper-citation">Published June 2025</div>
</div>

## Table of Contents

[Editorial](../../news/RJ-2025-2-editorial/) (p. 3)<br>*Rob J Hyndman*

### Contributed Research Articles

[The CRAN Task View Initiative](../../articles/RJ-2025-011/) (pp. 4-14)<br>*Achim Zeileis, Roger Bivand, Dirk Eddelbuettel, Kurt Hornik, Julia Piaskowski, Nathalie Vialaneix*

[boinet: An R Package for Bayesian Optimal Interval Design for Dose Finding Based on Both Efficacy and Toxicity Outcomes](../../articles/RJ-2025-012/) (pp. 15-34)<br>*Yusuke Yamaguchi, Kentaro Takeda, Kazushi Maruo*

[Partitioned Local Depth (PaLD) Community Analyses in R](../../articles/RJ-2025-013/) (pp. 35-55)<br>*Lucy D'Agostino McGowan, Katherine Moore, Kenneth S. Berenhaut*

[Student t-Lévy regression model in yuima](../../articles/RJ-2025-014/) (pp. 56-83)<br>*Hiroki Masuda, Lorenzo Mercuri, Yuma Uehara*

[Sfislands: An R Package for Accommodating Islands and Disjoint Zones in Areal Spatial Modelling](../../articles/RJ-2025-015/) (pp. 84-108)<br>*Kevin Horan, Katarina Domijan, Chris Brunsdon*

[rPDBapi: A Comprehensive R Package Interface for Accessing the Protein Data Bank](../../articles/RJ-2025-016/) (pp. 109-145)<br>*Selcuk Korkmaz, Bilge Eren Yamasan*

[rqPen: An R Package for Penalized Quantile Regression](../../articles/RJ-2025-017/) (pp. 146-175)<br>*Ben Sherwood, Shaobo Li, Adam Maidman*

[bartcs: An R Package for Bayesian Nonparametric Adjustment for Confounding](../../articles/RJ-2025-019/) (pp. 176-206)<br>*Yeonghoon Yoo, Chanmin Kim (corresponding author)*

[MSmix: An R Package for clustering partial rankings via mixtures of Mallows Models with Spearman distance](../../articles/RJ-2025-020/) (pp. 206-231)<br>*Marta Crispino, Cristina Mollica, Lucia Modugno*

[CvmortalityMult: Cross-Validation for Multi-Population Mortality Models](../../articles/RJ-2025-018/) (pp. 231-258)<br>*David Atance, Ana Debón*

### News and Notes

[Bioconductor Notes, September 2025](../../news/RJ-2025-2-bioconductor/) (pp. 258-261)<br>*Maria Doyle, Bioconductor Community Manager, Bioconductor Core Developer Team*

[Changes on CRAN](../../news/RJ-2025-2-cran/) (pp. 262-263)<br>*Kurt Hornik, Uwe Ligges, Achim Zeileis*

[R Foundation News](../../news/RJ-2025-2-rfoundation/) (p. 264)<br>*Torsten Hothorn*

