---
title: "Volume 17, Issue 1"
date: "2025-03-01"
page-layout: full
title-block-banner: true
toc: true
---

<div class="paper-card full-bleed">
  <p class="paper-links">
    <i class="fa-regular fa-file-pdf"></i>
    <a href="2025-1.pdf">Download Complete Issue (PDF)</a>
  </p>
  <div class="paper-citation">Published March 2025</div>
</div>

## Table of Contents

[Editorial](../../news/RJ-2025-1-editorial/) (pp. 3-4)<br>*Rob J Hyndman*

### Contributed Research Articles

[SIREN: A Hybrid CFA-EFA R Package for Controlling Acquiescence in Restricted Factorial Solutions](../../articles/RJ-2025-001/) (pp. 5-23)<br>*David Navarro-Gonzalez, Pere J. Ferrando, Fabia Morales-Vives, Ana Hernandez-Dorado*

[Random Forests for Time-Fixed and Time-Dependent Predictors: The DynForest R Package](../../articles/RJ-2025-002/) (pp. 24-46)<br>*Anthony Devaux, Cécile Proust-Lima, Robin Genuer*

[LCCR: An R Package for Inference on Latent Class Models for Capture-Recapture Data with Covariates](../../articles/RJ-2025-003/) (pp. 47-66)<br>*Francesco Bartolucci, Antonio Forcina*

[spheresmooth: An R Package for Penalized Piecewise Geodesic Curve Fitting on a Sphere](../../articles/RJ-2025-004/) (pp. 67-87)<br>*Jae-Hwan Jhong, Seyoung Lee, Ja-Yong Koo, Kwan-Young Bak*

[Space-Time Smoothing of Survey Outcomes using the R Package SUMMER](../../articles/RJ-2025-005/) (pp. 88-107)<br>*Zehang Richard Li, Bryan D Martin, Tracy Qi Dong, Geir-Arne Fuglstad, Jessica Godwin, John Paige, Andrea Riebler, Samuel J Clark, Jon Wakefield*

[latrend: A Framework for Clustering Longitudinal Data](../../articles/RJ-2025-006/) (pp. 108-135)<br>*Niek Den Teuling, Steffen Pauws, Edwin van den Heuvel*

[Structured Bayesian Regression Tree Models for Estimating Distributed Lag Effects: The R Package dlmtree](../../articles/RJ-2025-007/) (pp. 136-159)<br>*Seongwon Im, Ander Wilson, Daniel Mork*

[CDsampling: An R Package for Constrained D-Optimal Sampling in Paid Research Studies](../../articles/RJ-2025-008/) (pp. 160-179)<br>*Yifei Huang, Liping Tong, Jie Yang*

[panelPomp: Analysis of Panel Data via Partially Observed Markov Processes in R](../../articles/RJ-2025-009/) (pp. 180-199)<br>*Carles Bretó, Jesse Wheeler, Aaron A. King, Edward L. Ionides*

[SimEngine: A Modular Framework for Statistical Simulations in R](../../articles/RJ-2025-010/) (pp. 200-220)<br>*Avi Kenny, Charles J. Wolock*

### News and Notes

[Changes on CRAN](../../news/RJ-2025-1-cran/) (pp. 221-222)<br>*Kurt Hornik, Uwe Ligges, Achim Zeileis*

[R Foundation News](../../news/RJ-2025-1-rfoundation/) (p. 223)<br>*Torsten Hothorn*

